title: Aaron Wu 
url: 'http://aaronwwf.github.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2

#sidebar links
email: aaronwwf@qq.com 
website: blog.aaronwwf.com #do not add http://
linkedin: aaronwwf 
github: aaronwwf 